/** Common presets for designation/role fields (item 4). Custom entries are still allowed: titles vary too much to fully cover. */
export const JOB_TITLE_PRESETS = [
  "CEO",
  "CTO",
  "CIO",
  "CFO",
  "COO",
  "CMO",
  "CISO",
  "Founder",
  "Co-Founder",
  "VP Engineering",
  "VP Sales",
  "VP Marketing",
  "VP Product",
  "Head of Sales",
  "Head of Growth",
  "Head of Engineering",
  "Head of Product",
  "Director of Engineering",
  "Director of Sales",
  "Product Manager",
  "Engineering Manager",
  "Account Executive",
] as const
